services:
  site:
    image: "newspectrum/technovine:latest"
    build:
      dockerfile: "/Dockerfile"
    depends_on:
      - db
      - backend
    networks:
      - frontend
      - admin
    volumes:
      - site-storage:/var/site/storage
      - db-data:/var/db/data

  server:
    image: "ubuntu:latest"
    build:
      dockerfile: "./Technovine/backend/server/Dockerfile"
    networks:
      - backend
      - frontend
      - admin
    volumes:
      - server-storage:/var/server/storage
      - server-admin:/var/server/admin
      - db-data:/var/db/data
      - site-storage:/var/site/storage
    command: bash
        
  db:
    image: "mysql:latest"
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    depends_on:
      - backend
      - server
    networks:
      - backend
      - admin
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306

  backend:
    image: "nginx:latest"
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - backend
      - frontend
      - admin
    ports:
      - 80:80

secrets:
  db-password:
    file: "./Technovine/backend/db"